### ISSUE TITLE
有没模型文件啊？

### ISSUE THREAD

**Issue by lmw0320** [baseli/id_card_ocr#1]
如题，是否测试过? 精度多少?
看md说明，项目貌似还没完整？

**Comment by baseli** [comment]
自己没有进行模型训练，用到的模型都是 `paddle_ocr` 提供的，在 `interface` 目录下，[中英文超轻量OCR模型](https://github.com/PaddlePaddle/PaddleOCR/blob/develop/README_ch.md#pp-ocr-11%E7%B3%BB%E5%88%97%E6%A8%A1%E5%9E%8B%E5%88%97%E8%A1%A89%E6%9C%8817%E6%97%A5%E6%9B%B4%E6%96%B0)

由于我这边都是身份证复印件，相对来说比较规整，大概跑了100份左右，能有80多份识别出来

项目目前已经用 `qt` 写了界面，但是没有进行打包等的操作

**Comment by lmw0320** [comment]
哦，那是用的灰度图来识别的，而不是三通道的图片？
识别出来的结果是怎样的？如果直接用飞桨的模型文件，貌似没法识别生僻字吧？
我关注的是精度，不只是要识别出来，识别的准确度还要尽量高。。
我也试过飞桨的模型（包括轻量级的和resnet的模型文件），貌似准确度不够，比如会把姓名，识别成娃名，姓一名。性别识别成性剂等诸如此类的错误。。不知道你是否也遇到这种情况呢？

**Comment by baseli** [comment]
图片没做处理吗，是否是图片变形导致的，如果先图片矫正，然后裁剪要识别的位置单独识别会不会好一些

生僻字应该不行

**Comment by lmw0320** [comment]
我后面试了飞桨的升级版本1.1的，效果好了许多。
至少目前对生僻字识别效果不够，需要自己去训练，来提升效果。。
